[window]
opacity = 0.9
dynamic_title = false
[font]
normal = {family = "Jetbrains Mono"}
bold = {family = "Jetbrains Mono ", style = "Bold"}
italic = {family = "Jetbrains Mono ", style = "Italic"}
bold_italic = {family = "Jetbrains Mono ", style = "Bold-Italic"}

